import type { Method } from "./types.js";

export interface WorkloadProfile {
  id: string;
  display_name: string;
  description: string;
  method_weights: Record<Method, number>;
  /** If true, the dashboard applies the archival-completeness eligibility gate. */
  archive_heavy: boolean;
}

// Weights are illustrative per-workload method mixes (each profile sums to 100).
// All Method keys are present so the Record<Method, number> contract holds;
// a 0 means the workload effectively doesn't use that method.
export const PROFILES: readonly WorkloadProfile[] = [
  {
    id: "frontend",
    display_name: "Frontend",
    description: "Reading user transactions, balances, and recent activity",
    method_weights: {
      getTransaction: 30,
      getSignaturesForAddress: 25,
      getAccountInfo: 20,
      getTokenAccountsByOwner: 15,
      getBlock: 5,
      getSlot: 5,
      getProgramAccounts: 0,
      // New methods default to 0 (profile mix unchanged); revisit per-workload.
      getBalance: 0,
      getSupply: 0,
      getTokenSupply: 0,
      getTokenLargestAccounts: 0,
      getLatestBlockhash: 0,
      getTokenAccountBalance: 0,
      // 0 in every profile mix until per-workload tuned.
      getGenesisHash: 0,
      getEpochSchedule: 0,
      getInflationGovernor: 0,
      getInflationRate: 0,
      getBlockTime: 0,
      getBlockCommitment: 0,
      getBlocks: 0,
      getInflationReward: 0,
      getLeaderSchedule: 0,
      getBlockProduction: 0,
      getMaxRetransmitSlot: 0,
      getMaxShredInsertSlot: 0,
      getEpochInfo: 0,
      getBlockHeight: 0,
      getTransactionCount: 0,
      getVoteAccounts: 0,
      getRecentPerformanceSamples: 0,
      getIdentity: 0,
      getVersion: 0,
      getHealth: 0,
      isBlockhashValid: 0,
      getSlotLeader: 0,
      getSlotLeaders: 0,
      simulateTransaction: 0,
      simulateBundle: 0,
      // 0 in every profile mix until per-workload tuned.
      getMultipleAccounts: 0,
      getSignatureStatuses: 0,
      getMinimumBalanceForRentExemption: 0,
      getStakeMinimumDelegation: 0,
      getBlocksWithLimit: 0,
      getRecentPrioritizationFees: 0,
      getClusterNodes: 0,
      getLargestAccounts: 0,
      getFeeForMessage: 0,
      // 0 in every profile mix until per-workload tuned.
      getTransactionsForAddress: 0,
    },
    archive_heavy: false,
  },
  {
    id: "bot",
    display_name: "Bot",
    description: "Hot-path slot polling + tx confirmation",
    method_weights: {
      getSlot: 35,
      getTransaction: 35,
      getBlock: 15,
      getAccountInfo: 10,
      getSignaturesForAddress: 5,
      getProgramAccounts: 0,
      getTokenAccountsByOwner: 0,
      getBalance: 0,
      getSupply: 0,
      getTokenSupply: 0,
      getTokenLargestAccounts: 0,
      getLatestBlockhash: 0,
      getTokenAccountBalance: 0,
      // 0 in every profile mix until per-workload tuned.
      getGenesisHash: 0,
      getEpochSchedule: 0,
      getInflationGovernor: 0,
      getInflationRate: 0,
      getBlockTime: 0,
      getBlockCommitment: 0,
      getBlocks: 0,
      getInflationReward: 0,
      getLeaderSchedule: 0,
      getBlockProduction: 0,
      getMaxRetransmitSlot: 0,
      getMaxShredInsertSlot: 0,
      getEpochInfo: 0,
      getBlockHeight: 0,
      getTransactionCount: 0,
      getVoteAccounts: 0,
      getRecentPerformanceSamples: 0,
      getIdentity: 0,
      getVersion: 0,
      getHealth: 0,
      isBlockhashValid: 0,
      getSlotLeader: 0,
      getSlotLeaders: 0,
      simulateTransaction: 0,
      simulateBundle: 0,
      // 0 in every profile mix until per-workload tuned.
      getMultipleAccounts: 0,
      getSignatureStatuses: 0,
      getMinimumBalanceForRentExemption: 0,
      getStakeMinimumDelegation: 0,
      getBlocksWithLimit: 0,
      getRecentPrioritizationFees: 0,
      getClusterNodes: 0,
      getLargestAccounts: 0,
      getFeeForMessage: 0,
      // 0 in every profile mix until per-workload tuned.
      getTransactionsForAddress: 0,
    },
    archive_heavy: false,
  },
  {
    id: "indexer",
    display_name: "Indexer",
    description: "Backfill / streaming ingest + program-state scans",
    method_weights: {
      getBlock: 50,
      getProgramAccounts: 20,
      getTransaction: 15,
      getAccountInfo: 10,
      getSignaturesForAddress: 5,
      getSlot: 0,
      getTokenAccountsByOwner: 0,
      getBalance: 0,
      getSupply: 0,
      getTokenSupply: 0,
      getTokenLargestAccounts: 0,
      getLatestBlockhash: 0,
      getTokenAccountBalance: 0,
      // 0 in every profile mix until per-workload tuned.
      getGenesisHash: 0,
      getEpochSchedule: 0,
      getInflationGovernor: 0,
      getInflationRate: 0,
      getBlockTime: 0,
      getBlockCommitment: 0,
      getBlocks: 0,
      getInflationReward: 0,
      getLeaderSchedule: 0,
      getBlockProduction: 0,
      getMaxRetransmitSlot: 0,
      getMaxShredInsertSlot: 0,
      getEpochInfo: 0,
      getBlockHeight: 0,
      getTransactionCount: 0,
      getVoteAccounts: 0,
      getRecentPerformanceSamples: 0,
      getIdentity: 0,
      getVersion: 0,
      getHealth: 0,
      isBlockhashValid: 0,
      getSlotLeader: 0,
      getSlotLeaders: 0,
      simulateTransaction: 0,
      simulateBundle: 0,
      // 0 in every profile mix until per-workload tuned.
      getMultipleAccounts: 0,
      getSignatureStatuses: 0,
      getMinimumBalanceForRentExemption: 0,
      getStakeMinimumDelegation: 0,
      getBlocksWithLimit: 0,
      getRecentPrioritizationFees: 0,
      getClusterNodes: 0,
      getLargestAccounts: 0,
      getFeeForMessage: 0,
      // 0 in every profile mix until per-workload tuned.
      getTransactionsForAddress: 0,
    },
    archive_heavy: false,
  },
  {
    id: "archive_heavy",
    display_name: "Archive-heavy",
    description: "Historical research, biased to archival buckets",
    method_weights: {
      getBlock: 35,
      getTransaction: 35,
      getSignaturesForAddress: 15,
      getProgramAccounts: 15,
      getAccountInfo: 0,
      getSlot: 0,
      getTokenAccountsByOwner: 0,
      getBalance: 0,
      getSupply: 0,
      getTokenSupply: 0,
      getTokenLargestAccounts: 0,
      getLatestBlockhash: 0,
      getTokenAccountBalance: 0,
      // 0 in every profile mix until per-workload tuned.
      getGenesisHash: 0,
      getEpochSchedule: 0,
      getInflationGovernor: 0,
      getInflationRate: 0,
      getBlockTime: 0,
      getBlockCommitment: 0,
      getBlocks: 0,
      getInflationReward: 0,
      getLeaderSchedule: 0,
      getBlockProduction: 0,
      getMaxRetransmitSlot: 0,
      getMaxShredInsertSlot: 0,
      getEpochInfo: 0,
      getBlockHeight: 0,
      getTransactionCount: 0,
      getVoteAccounts: 0,
      getRecentPerformanceSamples: 0,
      getIdentity: 0,
      getVersion: 0,
      getHealth: 0,
      isBlockhashValid: 0,
      getSlotLeader: 0,
      getSlotLeaders: 0,
      simulateTransaction: 0,
      simulateBundle: 0,
      // 0 in every profile mix until per-workload tuned.
      getMultipleAccounts: 0,
      getSignatureStatuses: 0,
      getMinimumBalanceForRentExemption: 0,
      getStakeMinimumDelegation: 0,
      getBlocksWithLimit: 0,
      getRecentPrioritizationFees: 0,
      getClusterNodes: 0,
      getLargestAccounts: 0,
      getFeeForMessage: 0,
      // 0 in every profile mix until per-workload tuned.
      getTransactionsForAddress: 0,
    },
    archive_heavy: true,
  },
];

export const DEFAULT_PROFILE: WorkloadProfile = PROFILES[0]!;
